config/routes.rb
Tkbbc::Application.routes.draw do
  resources :boards

end

app/models/board.rb
# encoding: utf-8

class Board < ActiveRecord::Base
  has_many :posts
  validates :title, presence: true, length: { maximum: 100 }
end

app/models/post.rb
# encoding: utf-8

class Post < ActiveRecord::Base
  belongs_to :board

  validates :body, length: {maximum: 1000}, presence: true
  #validates :board_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to :boards }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.slim
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      h2 = "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      ul
        - @board.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :title
    = f.text_field :title

  .actions = f.submit 'Save'

app/views/boards/edit.html.slim
h1 Editing board

== render 'form'

= link_to 'Show', @board
'|
= link_to 'Back', boards_path

app/views/boards/index.html.slim
h1 Listing boards

table
  thead
    tr
      th Title

  tbody
    - @boards.each do |board|
      tr
        td = board.title
        td = link_to 'Show', board
        td = link_to 'Edit', edit_board_path(board)
        td = link_to 'Destroy', board, data: {confirm: 'Are you sure?', method: :delete}

br

= link_to 'New Board', new_board_path

app/views/boards/new.html.slim
h1 New board

== render 'form'

= link_to 'Back', boards_path

app/views/boards/show.html.slim
p#notice = notice

p = @board.title


= link_to 'Edit', edit_board_path(@board)
'|
= link_to 'Back', boards_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tkbbc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>